language: c
sudo: required

os:
  - linux

compiler:
  - gcc

# don't create redundant code coverage reports
# - AUTOTOOLS=yes COVERAGE=yes BUILD=static
# - AUTOTOOLS=no COVERAGE=yes BUILD=shared
# - AUTOTOOLS=no COVERAGE=no BUILD=static

# further speed up day by day travis-ci builds
# re-enable this if you change the makefiles
# this will still catch all coding errors!
# - AUTOTOOLS=yes COVERAGE=no BUILD=static

env:
#  - AUTOTOOLS=no COVERAGE=no BUILD=shared
#  - AUTOTOOLS=no COVERAGE=yes BUILD=static
  - AUTOTOOLS=yes COVERAGE=no BUILD=shared

# currenty there are various issues when
# built with coverage, clang and autotools
# - AUTOTOOLS=yes COVERAGE=yes BUILD=shared

# matrix:
#  exclude:
#    - compiler: clang
#      env: AUTOTOOLS=yes COVERAGE=yes BUILD=static
#    - os: linux
#      env: AUTOTOOLS=no COVERAGE=no BUILD=shared
#    - os: osx
#      compiler: gcc
#    - os: osx
#      env: AUTOTOOLS=no COVERAGE=yes BUILD=static

# script: ./script/ci-build-libsass
# before_install: ./script/ci-install-deps
# install: ./script/ci-install-compiler
# after_success: ./script/ci-report-coverage

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq automake libtool build-essential
  - libtoolize
  - aclocal
  - autoheader
  - automake --add-missing
  - autoconf

script:
  - ./configure && make && sudo make install && sudo ldconfig && gcc -lease tests/ease.c -o ease-test && ./ease-test multi

notifications:
  slack: bc10:hM6F5WGBdYDX2fPAx0yKmkvj

